import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import { Inter, Manrope, Poppins } from "next/font/google";
import "./globals.css";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const popping = Poppins({
  variable: "--font-popping",
  weight: "400",
  subsets: ["latin"],
});
const manrope = Manrope({ variable: "--font-manrope", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AarogyaNIX MedTech Solutions",
  description: "Generated by create next app",
  icons: "/logo-icon.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg" href="/logo-icon.svg" />
      </head>

      <body
        className={`${inter.variable} ${popping.variable} ${manrope.variable} antialiased font-inter`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
